AllCops:
  Exclude:
    - 'doc/**/*'
    - 'doc/*'
    - 'spec/**/*'
    - 'spec/*'
  TargetRubyVersion: 2.7
require:
  - rubocop-performance
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
  AutoCorrect: true
Layout/IndentationConsistency:
  EnforcedStyle: normal
Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true
Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes
Style/AndOr:
  EnforcedStyle: conditionals
Metrics/ClassLength:
  CountComments: false
  Max: 500
Metrics/ModuleLength:
  CountComments: false
  Max: 500
Layout/EndAlignment:
  AutoCorrect: true
Layout/DefEndAlignment:
  AutoCorrect: true
Performance:
  Enabled: true
Style/AutoResourceCleanup:
  Description: 'Suggests the usage of an auto resource cleanup version of a method (if available).'
  Enabled: true
Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 50
Style/NumericLiterals:
  Enabled: false
Layout/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Lint/Debugger:        # Easy deletion of all debugger breakpoints. false for debug
  Enabled: true
Metrics/AbcSize:
  Max: 40
Metrics/CyclomaticComplexity:
  Max: 11
Style/DoubleNegation:
  Description: 'Checks for uses of double negation (!!).'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#no-bang-bang'
  Enabled: false
Style/AsciiComments:
  Description: 'Use only ascii symbols in comments.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#english-comments'
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Enabled: false
Style/SingleLineMethods:
  Description: 'Avoid single-line methods.'
  StyleGuide: '#no-single-line-methods'
  Enabled: false
Style/Lambda:
  EnforcedStyle: literal
Layout/DotPosition:
  Description: Checks the position of the dot in multi-line method calls.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#consistent-multi-line-chains
  Enabled: true
  EnforcedStyle: trailing
  SupportedStyles:
    - leading
    - trailing
Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
