# frozen_string_literal: true

# #Kinopoisk Unofficial API
#
#
#
# The version of the OpenAPI document: 2.0.1
# Contact: support@kinopoiskapiunofficial.tech
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 5.3.1
#

$LOAD_PATH.push File.expand_path("lib", __dir__)
require "kuapir/version"

Gem::Specification.new do |s|
  s.name        = "kuapir"
  s.version     = Kuapir::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Alexey Zhuravlev"]
  s.email       = ["alexey.g.zhuravlev@gmail.com"]
  s.summary     = "Kinopoisk Unofficial API Ruby Gem"
  s.description = "Kinopoisk Unofficial API предеставляет доступ к данным сайта https://www.kinopoisk.ru. Для доступа вы должны получить токен, который будет доступен после регистрации на <a href=\"https://kinopoiskapiunofficial.tech\">https://kinopoiskapiunofficial.tech</a> </br> <b>Ограничения:</b>  лимитов на общее кол-во запросов нет. Но есть на кол-во запросов в секунду. </br> Каждый пользователь имеет ограничение в <b>20 req/sec</b>. </br> <b>Некоторые</b> эндпоинты имеют свои собственные ограничения, они указаны в описании для статуса <b>429</b>. </br>"
  s.license     = "Unlicense"
  s.required_ruby_version = ">= 2.7"

  s.add_runtime_dependency "typhoeus", "~> 1.0", ">= 1.0.1"

  s.add_development_dependency "rspec", "~> 3.6", ">= 3.6.0"

  s.files         = `find *`.split("\n").uniq.sort.reject(&:empty?)
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
