# frozen_string_literal: true

# #Kinopoisk Unofficial API

# The version of the OpenAPI document: 2.0.1
# Contact: support@kinopoiskapiunofficial.tech
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 5.3.1
#

require "spec_helper"
require "json"

# Unit tests for Kuapir::PersonsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe "PersonsApi" do
  before do
    # run before each test
    @api_instance = Kuapir::PersonsApi.new
  end

  after do
    # run after each test
  end

  describe "test an instance of PersonsApi" do
    it "should create an instance of PersonsApi" do
      expect(@api_instance).to be_instance_of(Kuapir::PersonsApi)
    end
  end

  # unit tests for api_v1_persons_get
  # поиск актеров, режиссеров и т.д. по имени
  # Одна страница может содержать до 50 элементов в items.
  # @param name имя человека
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page номер страницы
  # @return [PersonByNameResponse]
  describe "api_v1_persons_get test" do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end
end
