# frozen_string_literal: true

# #Kinopoisk Unofficial API

# The version of the OpenAPI document: 2.0.1
# Contact: support@kinopoiskapiunofficial.tech
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 5.3.1
#

require "spec_helper"
require "json"
require "date"

# Unit tests for Kuapir::VideoResponseItems
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Kuapir::VideoResponseItems do
  let(:instance) { Kuapir::VideoResponseItems.new }

  describe "test an instance of VideoResponseItems" do
    it "should create an instance of VideoResponseItems" do
      expect(instance).to be_instance_of(Kuapir::VideoResponseItems)
    end
  end
  describe 'test attribute "url"' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "name"' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "site"' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["YOUTUBE", "KINOPOISK_WIDGET", "UNKNOWN"])
      # validator.allowable_values.each do |value|
      #   expect { instance.site = value }.not_to raise_error
      # end
    end
  end
end
