# frozen_string_literal: true

# #Kinopoisk Unofficial API
#
#
#
# The version of the OpenAPI document: 2.0.1
# Contact: support@kinopoiskapiunofficial.tech
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 5.3.1
# Common files
require "kuapir/api_client"
require "kuapir/api_error"
require "kuapir/version"
require "kuapir/configuration"

# Models
require "kuapir/models/box_office"
require "kuapir/models/box_office_response"
require "kuapir/models/company"
require "kuapir/models/country"
require "kuapir/models/digital_release_item"
require "kuapir/models/digital_release_response"
require "kuapir/models/distribution"
require "kuapir/models/distribution_response"
require "kuapir/models/episode"
require "kuapir/models/fact"
require "kuapir/models/fact_response"
require "kuapir/models/film"
require "kuapir/models/film_search_by_filters_response"
require "kuapir/models/film_search_by_filters_response_items"
require "kuapir/models/film_search_response"
require "kuapir/models/film_search_response_films"
require "kuapir/models/film_sequels_and_prequels_response"
require "kuapir/models/film_top_response"
require "kuapir/models/film_top_response_films"
require "kuapir/models/filters_response"
require "kuapir/models/filters_response_countries"
require "kuapir/models/filters_response_genres"
require "kuapir/models/genre"
require "kuapir/models/image_response"
require "kuapir/models/image_response_items"
require "kuapir/models/person_by_name_response"
require "kuapir/models/person_by_name_response_items"
require "kuapir/models/person_response"
require "kuapir/models/person_response_films"
require "kuapir/models/person_response_spouses"
require "kuapir/models/premiere_response"
require "kuapir/models/premiere_response_item"
require "kuapir/models/related_film_response"
require "kuapir/models/related_film_response_items"
require "kuapir/models/review_details_response"
require "kuapir/models/reviews_response"
require "kuapir/models/reviews_response_reviews"
require "kuapir/models/season"
require "kuapir/models/season_response"
require "kuapir/models/staff_response"
require "kuapir/models/video_response"
require "kuapir/models/video_response_items"

# APIs
require "kuapir/api/films_api"
require "kuapir/api/persons_api"
require "kuapir/api/reviews_api"
require "kuapir/api/staff_api"

module Kuapir
  class << self
    # Customize default settings for the SDK using block.
    #   Kuapir.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
