# frozen_string_literal: true

# #Kinopoisk Unofficial API

# The version of the OpenAPI document: 2.0.1
# Contact: support@kinopoiskapiunofficial.tech
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 5.3.1
#

require "spec_helper"

describe Kuapir::Configuration do
  let(:config) { Kuapir::Configuration.default }

  describe "#base_url" do
    it "should have the default value" do
      expect(config.base_url).to eq("https://kinopoiskapiunofficial.tech")
    end

    it "should remove trailing slashes" do
      [nil, "", "/", "//"].each do |base_path|
        config.base_path = base_path
        expect(config.base_url).to eq("https://kinopoiskapiunofficial.tech")
      end
    end
  end
end
