# frozen_string_literal: true

# #Kinopoisk Unofficial API

# The version of the OpenAPI document: 2.0.1
# Contact: support@kinopoiskapiunofficial.tech
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 5.3.1
#

require "spec_helper"

describe Kuapir::Configuration do
  let(:config) { Kuapir::Configuration.default }

  before(:each) do
    # uncomment below to setup host and base_path
    # require 'URI'
    # uri = URI.parse("https://kinopoiskapiunofficial.tech")
    # Kuapir.configure do |c|
    #   c.host = uri.host
    #   c.base_path = uri.path
    # end
  end

  describe "#base_url" do
    it "should have the default value" do
      # uncomment below to test default value of the base path
      # expect(config.base_url).to eq("https://kinopoiskapiunofficial.tech")
    end

    it "should remove trailing slashes" do
      [nil, "", "/", "//"].each do |base_path|
        config.base_path = base_path
        # uncomment below to test trailing slashes
        # expect(config.base_url).to eq("https://kinopoiskapiunofficial.tech")
      end
    end
  end
end
